export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR';

export const USER_SESSION_FETCH = 'USER_SESSION_FETCH';
export const USER_SESSION_FETCH_SUCCESS = 'USER_SESSION_FETCH_SUCCESS';
export const USER_SESSION_FETCH_ERROR = 'USER_SESSION_FETCH_ERROR';

