export const EMAIL_ADD = 'EMAIL_ADD';
export const EMAIL_ADD_SUCCESS = 'EMAIL_ADD_SUCCESS';
export const EMAIL_ADD_ERROR = 'EMAIL_ADD_ERROR';

export const EMAIL_FETCH_ALL = 'EMAIL_FETCH_ALL';
export const EMAIL_FETCH_ALL_SUCCESS = 'EMAIL_FETCH_ALL_SUCCESS';
export const EMAIL_FETCH_ALL_ERROR = 'EMAIL_FETCH_ALL_ERROR';

export const EMAIL_FETCH_THREAD = 'EMAIL_FETCH_THREAD';
export const EMAIL_FETCH_THREAD_SUCCESS = 'EMAIL_FETCH_THREAD_SUCCESS';
export const EMAIL_FETCH_THREAD_ERROR = 'EMAIL_FETCH_THREAD_ERROR';

export const EMAIL_MARK_READ = 'EMAIL_MARK_READ';
export const EMAIL_MARK_READ_SUCCESS = 'EMAIL_MARK_READ_SUCCESS';
export const EMAIL_MARK_READ_ERROR = 'EMAIL_MARK_READ_ERROR'; 

export const EMAIL_MARK_DELETE = 'EMAIL_MARK_DELETE';
export const EMAIL_MARK_DELETE_SUCCESS = 'EMAIL_MARK_DELETE_SUCCESS';
export const EMAIL_MARK_DELETE_ERROR = 'EMAIL_MARK_DELETE_ERROR'; 